
spring:
  application:
    name: Shop
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

server:
  servlet:
    context-path: /api

key:
  access: ${KEY_ACCESS}
  refresh: ${KEY_REFRESH}

messages:
  hello: Hello form Digital Ocean!

