spring:
  application:
    name: Shop
  datasource:
    url: jdbc:postgresql://localhost:5432/g_XX_shop
    username: postgres
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com
          debug: true



server:
  servlet:
    context-path: /api

key:
  access: ${KEY_ACCESS}
  refresh: ${KEY_REFRESH}

messages:
  hello: Hello form Local!

